#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# Super + D open launchermenu
riverctl map normal Super D spawn "~/.config/rofi/launchers/type-7/launcher.sh"

# Emable tap
riverctl input "pointer-2321-21128-SPPT2600:00_0911:5288_Touchpad" tap enabled

# Super + Shift + L hyprlock
riverctl map normal Super L spawn "hyprlock"

# Start waybar, swaync and swaybg
exec waybar &

exec swaync &

swaybg -i .config/Wallpapers/forest-blue.png & 

# Super+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal Super Return spawn kitty

# Super+Shift+Q to close the focused 
riverctl map normal Super+Shift Q close

# Super+N open notifications panel
riverctl map normal Super N spawn "swaync-client -op"

# Super+Shift+W to restart waybar
riverctl map normal Super+Shift W spawn "pkill waybar && waybar &"

# Super+M to player
riverctl map normal Super M spawn "~/.config/rofi/applets/bin/mpd.sh"

# Super+Q to open Quick Links
riverctl map normal Super Q spawn "~/.config/rofi/quicklinks/bin/quicklinks.sh"

# Super+Shift+S to exec grim
riverctl map normal Super+Shift S spawn 'sh ~/.config/river/script/capture.sh'

# Super+Shift+E to exec powermenu
riverctl map normal Super+Shift E spawn "sh ~/.config/rofi/powermenu/type-6/powermenu.sh"

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super+Shift Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super - send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super + send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Shift Left move left 100
riverctl map normal Super+Shift Down move down 100
riverctl map normal Super+Shift Up move up 100
riverctl map normal Super+Shift Right move right 100

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Control Right resize horizontal -100
riverctl map normal Super+Control Up resize vertical 100
riverctl map normal Super+Control Down resize vertical -100
riverctl map normal Super+Control Left resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))


    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Control+Shift[1-9] to focus tag [0-8] and to tag focused view with tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

done

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen


# Cambiar enfoque de ventana con Super + Flechas
riverctl map normal Super Left  focus-view left
riverctl map normal Super Right focus-view right
riverctl map normal Super Up    focus-view up
riverctl map normal Super Down  focus-view down

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F1 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F1 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode normal Super+Control Down spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

# Set background and border color
riverctl border-width 0

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 12 -outer-padding 12 &


# keyboard ES
riverctl keyboard-layout es
